# Generated by Django 5.1.7 on 2025-04-06 20:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Минимум 4 символа', max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Название камня')),
                ('main_image', models.ImageField(upload_to='stones/main/', verbose_name='Главное изображение')),
                ('another_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Альтернативное название')),
            ],
            options={
                'verbose_name': 'Камень',
                'verbose_name_plural': 'Камни',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название компании')),
                ('company_image', models.ImageField(upload_to='companies/', verbose_name='Логотип компании')),
                ('description', models.TextField(verbose_name='Описание компании')),
                ('created_at', models.DateField(verbose_name='Дата основания')),
                ('produced_stones', models.ManyToManyField(related_name='manufacturers', to='basic_page.infostone', verbose_name='Производимые камни')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='StoneDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название характеристики')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('image_description', models.ImageField(blank=True, upload_to='stones/descriptions/', verbose_name='Изображение для описания')),
                ('info_stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='basic_page.infostone', verbose_name='Связанный камень')),
            ],
            options={
                'verbose_name': 'Описание камня',
                'verbose_name_plural': 'Описания камней',
                'unique_together': {('info_stone', 'name')},
            },
        ),
    ]
