# Generated by Django 5.1.7 on 2025-04-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_at',
        ),
    ]
