# Generated by Django 5.1.7 on 2025-07-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_quartzstone_brand_stone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stone',
            name='material',
            field=models.CharField(choices=[('Кварцевый камень', 'Кварцевый камень'), ('Акриловый камень', 'Акриловый камень'), ('Натуральный камень', 'Натуральный камень'), ('Керамический камень', 'Керамический камень')], max_length=50, verbose_name='Материал камня'),
        ),
    ]
