# Generated by Django 5.1.7 on 2025-07-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_stone_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartzstone',
            name='color',
            field=models.CharField(choices=[('Бежевый', 'Бежевый'), ('Белый', 'Белый'), ('Коричневый', 'Коричневый'), ('Серый', 'Серый'), ('Темносерый', 'Темносерый'), ('Черный', 'Черный')], max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='quartzstone',
            name='faktura',
            field=models.CharField(choices=[('Матовая', 'Матовая'), ('Полированная', 'Полированная')], max_length=50, verbose_name='Фактура'),
        ),
        migrations.AlterField(
            model_name='quartzstone',
            name='link_serf',
            field=models.CharField(choices=[('q_cert.pdf', '#'), ('q_safe.pdf', '#')], max_length=50, verbose_name='Ссылка на сертификаты'),
        ),
        migrations.AlterField(
            model_name='quartzstone',
            name='texture',
            field=models.CharField(choices=[('Бетон', 'Бетон'), ('Мраморная', 'Мраморная'), ('Однотонная', 'Однотонная'), ('Тераццо', 'Тераццо')], max_length=50, verbose_name='Текстура'),
        ),
        migrations.AlterField(
            model_name='stone',
            name='country',
            field=models.CharField(choices=[('Кварцевый камень', 'Кварцевый камень')], max_length=50, verbose_name='Страна изготовления'),
        ),
    ]
