# Generated by Django 5.2.4 on 2025-07-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_quartzstone_color_alter_quartzstone_faktura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartzstone',
            name='link_serf',
            field=models.CharField(choices=[('https://drive.google.com/drive/folders/1YgXlFi8KKDzPHz5IheKJlbepOqd1sl3M', 'Caesarstone'), ('https://technistone.ru/info/certificates/', 'Technistone')], verbose_name='Ссылка на сертификаты'),
        ),
    ]
