# Generated by Django 5.2.4 on 2025-07-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_stone_priview_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartzstone',
            name='brand_stone',
            field=models.CharField(choices=[('Caesarstone', 'Caesarstone'), ('Technistone', 'Technistone')], max_length=50, verbose_name='Бренд'),
        ),
    ]
