# Generated by Django 5.2.4 on 2025-08-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_quartzstone_brand_stone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acrylicstone',
            name='brand_stone',
            field=models.CharField(choices=[('Hanex', 'Hanex'), ('Durasein', 'Durasein')], max_length=50, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='acrylicstone',
            name='color',
            field=models.CharField(choices=[('Бежевый', 'Бежевый'), ('Белый', 'Белый'), ('Жёлтый', 'Жёлтый'), ('Коричневый', 'Коричневый'), ('Светло-голубой', 'Светло-голубой'), ('Светло-коричневый', 'Светло-коричневый'), ('Светло-серый', 'Светло-серый'), ('Серый', 'Серый'), ('Темно-коричневый', 'Темно-коричневый'), ('Темно-красный', 'Темно-красный'), ('Темно-серый', 'Темно-серый'), ('Черный', 'Черный'), ('Зеленый', 'Зеленый'), ('Красный', 'Красный'), ('Оранжевый', 'Оранжевый'), ('Светло-зеленый', 'Светло-зеленый'), ('Синий', 'Синий')], max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='acrylicstone',
            name='link_serf',
            field=models.CharField(choices=[('https://ssd.su/upload/iblock/74f/3hlh6ielnui9v0yw53ua78vqy1iikpdp.zip', 'Сертификат Hanex(ССД)'), ('https://ssd.su/upload/iblock/a62/2n2gdb8s43pfs2bqjt7g6wdwdx0vwvcf.zip', 'Сертификат Durasein(ССД)')], max_length=200, verbose_name='Ссылка на сертификаты'),
        ),
        migrations.AlterField(
            model_name='acrylicstone',
            name='texture',
            field=models.CharField(choices=[('Мраморная', 'Мраморная'), ('Однотонная', 'Однотонная'), ('Пески', 'Пески'), ('Средний чип', 'Средний чип'), ('Крупный чип', 'Крупный чип'), ('Белый', 'Белый')], max_length=50, verbose_name='Текстура'),
        ),
        migrations.AlterField(
            model_name='stone',
            name='country',
            field=models.CharField(choices=[('Чехия', 'Чехия'), ('Израиль', 'Израиль'), ('Южная Корея', 'Южная Корея'), ('Китай', 'Китай')], max_length=50, verbose_name='Страна изготовления'),
        ),
    ]
