# Generated by Django 5.2.4 on 2026-06-18 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_acrylicstone_brand_stone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acrylicstone',
            name='brand_stone',
            field=models.CharField(blank=True, choices=[('Hanex', 'Hanex'), ('Durasein', 'Durasein')], max_length=50, null=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='acrylicstone',
            name='color',
            field=models.CharField(blank=True, choices=[('Бежевый', 'Бежевый'), ('Белый', 'Белый'), ('Жёлтый', 'Жёлтый'), ('Коричневый', 'Коричневый'), ('Светло-голубой', 'Светло-голубой'), ('Светло-коричневый', 'Светло-коричневый'), ('Светло-серый', 'Светло-серый'), ('Серый', 'Серый'), ('Темно-коричневый', 'Темно-коричневый'), ('Темно-красный', 'Темно-красный'), ('Темно-серый', 'Темно-серый'), ('Черный', 'Черный'), ('Зеленый', 'Зеленый'), ('Красный', 'Красный'), ('Оранжевый', 'Оранжевый'), ('Светло-зеленый', 'Светло-зеленый'), ('Синий', 'Синий')], max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='acrylicstone',
            name='faktura',
            field=models.CharField(blank=True, choices=[('silky', 'Шелковистая'), ('pearl', 'Жемчужная')], max_length=50, null=True, verbose_name='Фактура'),
        ),
        migrations.AlterField(
            model_name='acrylicstone',
            name='link_serf',
            field=models.CharField(blank=True, choices=[('https://ssd.su/upload/iblock/74f/3hlh6ielnui9v0yw53ua78vqy1iikpdp.zip', 'Сертификат Hanex(ССД)'), ('https://ssd.su/upload/iblock/a62/2n2gdb8s43pfs2bqjt7g6wdwdx0vwvcf.zip', 'Сертификат Durasein(ССД)')], max_length=200, null=True, verbose_name='Ссылка на сертификаты'),
        ),
        migrations.AlterField(
            model_name='acrylicstone',
            name='texture',
            field=models.CharField(blank=True, choices=[('Мраморная', 'Мраморная'), ('Однотонная', 'Однотонная'), ('Пески', 'Пески'), ('Средний чип', 'Средний чип'), ('Крупный чип', 'Крупный чип'), ('Белый', 'Белый')], max_length=50, null=True, verbose_name='Текстура'),
        ),
        migrations.AlterField(
            model_name='ceramicsstone',
            name='brand_stone',
            field=models.CharField(blank=True, choices=[('ceram_p', 'CeramPro'), ('tile_m', 'TileMaster')], max_length=50, null=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='ceramicsstone',
            name='color',
            field=models.CharField(blank=True, choices=[('graphite', 'Графитовый'), ('ivory', 'Слоновая кость')], max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='ceramicsstone',
            name='faktura',
            field=models.CharField(blank=True, choices=[('glassy', 'Стекловидная'), ('rustic', 'Рустикальная')], max_length=50, null=True, verbose_name='Фактура'),
        ),
        migrations.AlterField(
            model_name='ceramicsstone',
            name='link_serf',
            field=models.CharField(blank=True, choices=[('ceram_cert.pdf', 'Сертификат керамики'), ('heat_res.pdf', 'Термостойкость')], max_length=50, null=True, verbose_name='Ссылка на сертификаты'),
        ),
        migrations.AlterField(
            model_name='ceramicsstone',
            name='texture',
            field=models.CharField(blank=True, choices=[('geometric', 'Геометрическая'), ('concrete', 'Бетон')], max_length=50, null=True, verbose_name='Текстура'),
        ),
        migrations.AlterField(
            model_name='naturalstone',
            name='brand_stone',
            field=models.CharField(blank=True, choices=[('n_stone', 'NatureStone'), ('m_gems', 'MountainGems')], max_length=50, null=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='naturalstone',
            name='color',
            field=models.CharField(blank=True, choices=[('forest', 'Лесной'), ('sandstone', 'Песчаник')], max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='naturalstone',
            name='faktura',
            field=models.CharField(blank=True, choices=[('rocky', 'Скальная'), ('aged', 'Состаренная')], max_length=50, null=True, verbose_name='Фактура'),
        ),
        migrations.AlterField(
            model_name='naturalstone',
            name='link_serf',
            field=models.CharField(blank=True, choices=[('nat_cert.pdf', 'Сертификат природного камня'), ('origin.pdf', 'Сертификат происхождения')], max_length=50, null=True, verbose_name='Ссылка на сертификаты'),
        ),
        migrations.AlterField(
            model_name='naturalstone',
            name='texture',
            field=models.CharField(blank=True, choices=[('cracked', 'Трещиноватая'), ('layered', 'Слоистая')], max_length=50, null=True, verbose_name='Текстура'),
        ),
        migrations.AlterField(
            model_name='quartzstone',
            name='brand_stone',
            field=models.CharField(blank=True, choices=[('Caesarstone', 'Caesarstone'), ('Technistone', 'Technistone')], max_length=50, null=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='quartzstone',
            name='color',
            field=models.CharField(blank=True, choices=[('Бежевый', 'Бежевый'), ('Белый', 'Белый'), ('Коричневый', 'Коричневый'), ('Серый', 'Серый'), ('Темносерый', 'Темносерый'), ('Черный', 'Черный')], max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='quartzstone',
            name='faktura',
            field=models.CharField(blank=True, choices=[('Матовая', 'Матовая'), ('Полированная', 'Полированная')], max_length=50, null=True, verbose_name='Фактура'),
        ),
        migrations.AlterField(
            model_name='quartzstone',
            name='link_serf',
            field=models.CharField(blank=True, choices=[('https://drive.google.com/drive/folders/1YgXlFi8KKDzPHz5IheKJlbepOqd1sl3M', 'Caesarstone'), ('https://technistone.ru/info/certificates/', 'Technistone')], null=True, verbose_name='Ссылка на сертификаты'),
        ),
        migrations.AlterField(
            model_name='quartzstone',
            name='texture',
            field=models.CharField(blank=True, choices=[('Бетон', 'Бетон'), ('Мраморная', 'Мраморная'), ('Однотонная', 'Однотонная'), ('Тераццо', 'Тераццо')], max_length=50, null=True, verbose_name='Текстура'),
        ),
        migrations.AlterField(
            model_name='stone',
            name='about_brand',
            field=models.TextField(blank=True, null=True, verbose_name='О бренде'),
        ),
        migrations.AlterField(
            model_name='stone',
            name='abt_prise',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(9999999.99)], verbose_name='Примерная цена'),
        ),
        migrations.AlterField(
            model_name='stone',
            name='article',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='stone',
            name='country',
            field=models.CharField(blank=True, choices=[('Чехия', 'Чехия'), ('Израиль', 'Израиль'), ('Южная Корея', 'Южная Корея'), ('Китай', 'Китай')], max_length=50, null=True, verbose_name='Страна изготовления'),
        ),
        migrations.AlterField(
            model_name='stone',
            name='material',
            field=models.CharField(blank=True, choices=[('Кварцевый камень', 'Кварцевый камень'), ('Акриловый камень', 'Акриловый камень'), ('Натуральный камень', 'Натуральный камень'), ('Керамический камень', 'Керамический камень')], max_length=50, null=True, verbose_name='Материал камня'),
        ),
        migrations.AlterField(
            model_name='stone',
            name='thickness',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Толщина (мм)'),
        ),
    ]
