# Generated by Django 5.2.4 on 2026-06-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_acrylicstone_brand_stone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acrylicstone',
            name='brand_stone',
            field=models.CharField(blank=True, choices=[('Hanex', 'Hanex'), ('Durasein', 'Durasein'), ('Primax', 'Primax')], max_length=50, null=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='acrylicstone',
            name='color',
            field=models.CharField(blank=True, choices=[('Бежевый', 'Бежевый'), ('Белый', 'Белый'), ('Жёлтый', 'Жёлтый'), ('Коричневый', 'Коричневый'), ('Светло-голубой', 'Светло-голубой'), ('Светло-коричневый', 'Светло-коричневый'), ('Светло-серый', 'Светло-серый'), ('Серый', 'Серый'), ('Темно-коричневый', 'Темно-коричневый'), ('Темно-красный', 'Темно-красный'), ('Темно-серый', 'Темно-серый'), ('Черный', 'Черный'), ('Зеленый', 'Зеленый'), ('Красный', 'Красный'), ('Оранжевый', 'Оранжевый'), ('Светло-зеленый', 'Светло-зеленый'), ('Синий', 'Синий'), ('РЎРІРµС‚Р»С‹Р№', 'РЎРІРµС‚Р»С‹Р№'), ('РўРµРјРЅС‹Р№', 'РўРµРјРЅС‹Р№'), ('РњРЅРѕРіРѕС†РІРµС‚РЅС‹Р№', 'РњРЅРѕРіРѕС†РІРµС‚РЅС‹Р№')], max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='acrylicstone',
            name='texture',
            field=models.CharField(blank=True, choices=[('Мраморная', 'Мраморная'), ('Однотонная', 'Однотонная'), ('Пески', 'Пески'), ('Средний чип', 'Средний чип'), ('Крупный чип', 'Крупный чип'), ('Белый', 'Белый'), ('РџСЂР°Р№РјР°РєСЃ РїСЂРµРјРёР°Р»СЊРЅС‹Р№ / Primax premium', 'РџСЂР°Р№РјР°РєСЃ РїСЂРµРјРёР°Р»СЊРЅС‹Р№ / Primax premium'), ('РџСЂР°Р№РјР°РєСЃ Р‘Р°Р·РѕРІС‹Р№ / Primax Basic', 'РџСЂР°Р№РјР°РєСЃ Р‘Р°Р·РѕРІС‹Р№ / Primax Basic'), ('РџСЂР°Р№РјР°РєСЃ РјСЂР°РјРѕСЂРЅС‹Р№ / Primax marble', 'РџСЂР°Р№РјР°РєСЃ РјСЂР°РјРѕСЂРЅС‹Р№ / Primax marble')], max_length=70, null=True, verbose_name='Текстура'),
        ),
        migrations.AlterField(
            model_name='quartzstone',
            name='brand_stone',
            field=models.CharField(blank=True, choices=[('Caesarstone', 'Caesarstone'), ('Technistone', 'Technistone'), ('PrimaxQuartz', 'Primax Quartz')], max_length=50, null=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='quartzstone',
            name='color',
            field=models.CharField(blank=True, choices=[('Бежевый', 'Бежевый'), ('Белый', 'Белый'), ('Коричневый', 'Коричневый'), ('Серый', 'Серый'), ('Темносерый', 'Темносерый'), ('Черный', 'Черный'), ('РЎРІРµС‚Р»С‹Р№', 'РЎРІРµС‚Р»С‹Р№'), ('РўРµРјРЅС‹Р№', 'РўРµРјРЅС‹Р№'), ('РњРЅРѕРіРѕС†РІРµС‚РЅС‹Р№', 'РњРЅРѕРіРѕС†РІРµС‚РЅС‹Р№')], max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='quartzstone',
            name='faktura',
            field=models.CharField(blank=True, choices=[('Матовая', 'Матовая'), ('Полированная', 'Полированная'), ('РЎС‚Р°РЅРґР°СЂС‚РЅР°СЏ', 'РЎС‚Р°РЅРґР°СЂС‚РЅР°СЏ'), ('FBP', 'FBP')], max_length=50, null=True, verbose_name='Фактура'),
        ),
        migrations.AlterField(
            model_name='quartzstone',
            name='link_serf',
            field=models.CharField(blank=True, choices=[('https://drive.google.com/drive/folders/1YgXlFi8KKDzPHz5IheKJlbepOqd1sl3M', 'Caesarstone'), ('https://technistone.ru/info/certificates/', 'Technistone'), ('https://primax.pro/', 'Primax')], null=True, verbose_name='Ссылка на сертификаты'),
        ),
        migrations.AlterField(
            model_name='quartzstone',
            name='texture',
            field=models.CharField(blank=True, choices=[('Бетон', 'Бетон'), ('Мраморная', 'Мраморная'), ('Однотонная', 'Однотонная'), ('Тераццо', 'Тераццо'), ('РџСЂР°Р№РјР°РєСЃ РљРІР°СЂС† / PrimaxQuartz', 'РџСЂР°Р№РјР°РєСЃ РљРІР°СЂС† / PrimaxQuartz'), ('РџСЂР°Р№РјР°РєСЃ РљРІР°СЂС† Р¤СЂРµСЃРєРѕ / PrimaxQuartz Fresco', 'РџСЂР°Р№РјР°РєСЃ РљРІР°СЂС† Р¤СЂРµСЃРєРѕ / PrimaxQuartz Fresco')], max_length=70, null=True, verbose_name='Текстура'),
        ),
    ]
